global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "service1"
    static_configs:
      - targets:
          - "service1:8000"

  - job_name: "service2"
    static_configs:
      - targets:
          - "service2:8000"

  - job_name: "service3"
    static_configs:
      - targets:
          - "service3:8000"
